baseURL = "http://dev.monikaschubert.com/"

DefaultContentLanguage = "en"
enableMissingTranslationPlaceholders = true

sectionPagesMenu = "main"

[blackfriday]
angledQuotes = true
hrefTargetBlank = true


[Languages]

[Languages.en]
  title = "Monika Schubert"
  description = "Artist"
  languageName = "English"
  languageCode = "en-us"
  weight = 1

[Languages.de]
  title = "Monika Schubert"
  description = "KÃ¼nstlerin"
  languageName = "Deutsch"
  languageCode = "de-de"
  weight = 2

